### ISSUE TITLE
[question] Plans.

### ISSUE THREAD

**Issue by Si1kn** [AlephInfinity1/ForgeBlock#4]
Hi!
What are you planning to-do with this mod?
Are you looking to add most of the items to this mod? 
Thanks Si1kn.

**Comment by AlephInfinity1** [comment]
Heya, and sorry for the late response,

Initially, I wrote this mod in order to create an exact replica of Hypixel's SkyBlock. However, some of the most recent updates, the community centre one, for instance, are incompatible with the singleplayer nature of mods, so my plan changed to keeping the original SkyBlock as close as possible while adding some custom stuff for features that cannot be replicated in Singleplayer (bazaar, dungeons, community centre and etc.). I might add more custom stuff later in development after I catch up with all the current SkyBlock features.

Thanks for your support! :)

Cheers, AlephInfinity1
